### ISSUE TITLE
Higher Accuracy without Distribution Calibration

### ISSUE THREAD

**Issue by shaktikshri** [ShuoYang-1998/Few_Shot_Distribution_Calibration#15]
Hi there,
Thanks for the neat implementation here on GitHub.

I am trying to replicate your results and I'm consistently seeing higher accuracies for models trained on just (support_data, support_label) without any (sampled_data, sampled_label) (thus without any distribution calibration).
I couldn't find a reference in your paper about how much your calibration approach increases the accuracy compared to models just trained on (support_data, support_label) pairs.

For reference,
```
Start classification for 200 tasks...
miniImagenet 5 way 5 shot  ACC : 0.821400
miniImagenet 5 way 5 shot Accuracy without Calibration : 0.840067

Start classification for 20 tasks...
miniImagenet 5 way 5 shot  ACC : 0.818667
miniImagenet 5 way 5 shot Accuracy without Calibration : 0.831333
```
Wanted to check if I'm missing something or is this result expected.

**Comment by ucasligang** [comment]
Hi, I ran the experiment again and it did not improve(but fall down a little)in 5way-5shot tasks but it was not as good as what you showed.
`
Start classification for 200 tasks...
After DC: miniImagenet 5 way 5 shot  ACC : 0.830067
Without DC: miniImagenet 5 way 5 shot  ACC : 0.831200`

**Comment by shaktikshri** [comment]
Did you keep the tukey transformation for 'Without DC' experiment? For me just doing Tukey is outweighing entire calibration methodology.

**Comment by ucasligang** [comment]
Oh,sorry,I just forgotten throw away the tukey transformation for 'Without DC' experiment.But I think the mean and variance of support set is more reliable when suppport samples is more sufficient(5-shot),so the mean and variance should be a bigger part when calibrate the distribution.However,the authors of this work only calibrate the distribution like 1-shot tasks.Maybe the author just ignored it,because the results is more better in 1-shot tasks after calibrating the distribution.

**Comment by shaktikshri** [comment]
I would be really surprised if results from 'doing nothing' are disregarded completely, even when 5 way 5 shot results are demonstrated in the paper and shown to perform better than other existing approach (doing nothing or No DC is just another approach)
I think I'm missing something here, if any of the authors can help clarify this that will be great!

**Comment by ucasligang** [comment]
I checked the results with and without DC on 1 shot.
`
Start classification for 20 tasks..
After DC:miniImagenet 5 way 1 shot  ACC : 0.694000
Without DC:miniImagenet 5 way 1 shot  ACC : 0.523333
`

**Comment by ShuoYang-1998** [comment]
Hi, thanks @ucasligang for response. In 5 shot case, the ground-truth distribution can be better uncovered by the support set thus the calibrated distribution becomes not that reliable. Maybe you can come up a better calibration strategy for 5-or-more shot case such as assigning a higher weight for the support set and a lower weight for the generated examples. However, I would like to claim that the Tukey transformation is also a critical component of the proposed distribution calibration strategy since it also calibrate the distribution of target classes instead of 'not doing anything'. 
Thanks.
